name: Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-14
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/actions/wrapper-validation@v3.5.0
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew build
      - name: Final checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        with:
          name: Lint-report
          path: app/build/reports/lint-results.html
