name: Pull Request

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-14
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/actions/wrapper-validation@v5
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew build
      - name: Final checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        with:
          name: Lint-report
          path: app/build/reports/lint-results.html
